name: CI

on:
  push:
    branches: [main, dev, feature/**]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4

      # Set up Python and cache Poetry’s virtual-env between runs
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-interaction --no-root

      - name: Run lint & type checks
        run: poetry run pre-commit run --all-files
