name: CI

on:
  push:
    branches: [main, dev, feature/**]
  pull_request:

env:
  POETRY_VIRTUALENVS_IN_PROJECT: "true"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      # 1. Check out code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Install Poetry — robust version
      - name: Install Poetry
        id: install-poetry
        run: |
          # If Poetry already on PATH (e.g. cached), skip
          if command -v poetry >/dev/null 2>&1; then
            echo "Poetry already installed"; exit 0
          fi
          # Otherwise install the official way
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      # 4. Show Poetry version to confirm it was added
      - name: Check Poetry
        run: poetry --version

      # 5. Install dependencies from lock / pyproject
      - name: Install project deps
        run: poetry install --no-interaction --no-root

      # 6. Run Ruff + MyPy pre-commit hooks
      - name: Lint & type-check
        run: poetry run pre-commit run --all-files
